name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [released]

env:
  REGISTRY: docker.io
  IMAGE_NAME: noredlace/wakfu-sublimations

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: wakfu-sublimations/package-lock.json

    - name: Install dependencies
      run: npm ci
      working-directory: wakfu-sublimations

    - name: Run linting
      run: npm run lint
      working-directory: wakfu-sublimations

    - name: Build application
      run: npm run build
      working-directory: wakfu-sublimations

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: 'wakfu-sublimations'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  build-and-test-docker:
    name: Build and Test Docker Image
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag wakfu-sublimations:test
      working-directory: wakfu-sublimations

    - name: Test Docker image
      run: |
        docker run --rm wakfu-sublimations:test nginx -t
        docker run --rm -d --name test-container -p 8080:80 wakfu-sublimations:test
        sleep 10
        curl -f http://localhost:8080/ || exit 1
        docker stop test-container
      working-directory: wakfu-sublimations

  publish:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    needs: [test, security-scan, build-and-test-docker]
    if: github.event_name == 'release' || startsWith(github.ref, 'refs/tags/v')
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./wakfu-sublimations
        file: ./wakfu-sublimations/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
